 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/congregations", type: :request do
  # Congregation. As you add validations to Congregation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Congregation.create! valid_attributes
      get congregations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      congregation = Congregation.create! valid_attributes
      get congregation_url(congregation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_congregation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      congregation = Congregation.create! valid_attributes
      get edit_congregation_url(congregation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Congregation" do
        expect {
          post congregations_url, params: { congregation: valid_attributes }
        }.to change(Congregation, :count).by(1)
      end

      it "redirects to the created congregation" do
        post congregations_url, params: { congregation: valid_attributes }
        expect(response).to redirect_to(congregation_url(Congregation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Congregation" do
        expect {
          post congregations_url, params: { congregation: invalid_attributes }
        }.to change(Congregation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post congregations_url, params: { congregation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested congregation" do
        congregation = Congregation.create! valid_attributes
        patch congregation_url(congregation), params: { congregation: new_attributes }
        congregation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the congregation" do
        congregation = Congregation.create! valid_attributes
        patch congregation_url(congregation), params: { congregation: new_attributes }
        congregation.reload
        expect(response).to redirect_to(congregation_url(congregation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        congregation = Congregation.create! valid_attributes
        patch congregation_url(congregation), params: { congregation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested congregation" do
      congregation = Congregation.create! valid_attributes
      expect {
        delete congregation_url(congregation)
      }.to change(Congregation, :count).by(-1)
    end

    it "redirects to the congregations list" do
      congregation = Congregation.create! valid_attributes
      delete congregation_url(congregation)
      expect(response).to redirect_to(congregations_url)
    end
  end
end
