 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/public_speakers", type: :request do
  # PublicSpeaker. As you add validations to PublicSpeaker, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PublicSpeaker.create! valid_attributes
      get public_speakers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      public_speaker = PublicSpeaker.create! valid_attributes
      get public_speaker_url(public_speaker)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_public_speaker_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      public_speaker = PublicSpeaker.create! valid_attributes
      get edit_public_speaker_url(public_speaker)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PublicSpeaker" do
        expect {
          post public_speakers_url, params: { public_speaker: valid_attributes }
        }.to change(PublicSpeaker, :count).by(1)
      end

      it "redirects to the created public_speaker" do
        post public_speakers_url, params: { public_speaker: valid_attributes }
        expect(response).to redirect_to(public_speaker_url(PublicSpeaker.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PublicSpeaker" do
        expect {
          post public_speakers_url, params: { public_speaker: invalid_attributes }
        }.to change(PublicSpeaker, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post public_speakers_url, params: { public_speaker: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested public_speaker" do
        public_speaker = PublicSpeaker.create! valid_attributes
        patch public_speaker_url(public_speaker), params: { public_speaker: new_attributes }
        public_speaker.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the public_speaker" do
        public_speaker = PublicSpeaker.create! valid_attributes
        patch public_speaker_url(public_speaker), params: { public_speaker: new_attributes }
        public_speaker.reload
        expect(response).to redirect_to(public_speaker_url(public_speaker))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        public_speaker = PublicSpeaker.create! valid_attributes
        patch public_speaker_url(public_speaker), params: { public_speaker: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested public_speaker" do
      public_speaker = PublicSpeaker.create! valid_attributes
      expect {
        delete public_speaker_url(public_speaker)
      }.to change(PublicSpeaker, :count).by(-1)
    end

    it "redirects to the public_speakers list" do
      public_speaker = PublicSpeaker.create! valid_attributes
      delete public_speaker_url(public_speaker)
      expect(response).to redirect_to(public_speakers_url)
    end
  end
end
