 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/souls", type: :request do
  # Soul. As you add validations to Soul, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Soul.create! valid_attributes
      get souls_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      soul = Soul.create! valid_attributes
      get soul_url(soul)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_soul_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      soul = Soul.create! valid_attributes
      get edit_soul_url(soul)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Soul" do
        expect {
          post souls_url, params: { soul: valid_attributes }
        }.to change(Soul, :count).by(1)
      end

      it "redirects to the created soul" do
        post souls_url, params: { soul: valid_attributes }
        expect(response).to redirect_to(soul_url(Soul.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Soul" do
        expect {
          post souls_url, params: { soul: invalid_attributes }
        }.to change(Soul, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post souls_url, params: { soul: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested soul" do
        soul = Soul.create! valid_attributes
        patch soul_url(soul), params: { soul: new_attributes }
        soul.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the soul" do
        soul = Soul.create! valid_attributes
        patch soul_url(soul), params: { soul: new_attributes }
        soul.reload
        expect(response).to redirect_to(soul_url(soul))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        soul = Soul.create! valid_attributes
        patch soul_url(soul), params: { soul: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested soul" do
      soul = Soul.create! valid_attributes
      expect {
        delete soul_url(soul)
      }.to change(Soul, :count).by(-1)
    end

    it "redirects to the souls list" do
      soul = Soul.create! valid_attributes
      delete soul_url(soul)
      expect(response).to redirect_to(souls_url)
    end
  end
end
