1:
  outline_name: 'HOW WELL DO YOU KNOW GOD?'
  outline_date: '9/15'
  outline_time: 30
  outline_note: 'Knowing God involves more than knowing facts about him. We must become intimately acquainted with Jehovah’s deeds and qualities and act in harmony with that knowledge. Motivate listeners to come to know Jehovah well and gain his approval.'
  subheadings: ['COMING TO KNOWGOD “MEANS EVERLASTING LIFE”', 'HOWCAN YOU COME TO KNOW JEHOVAH?', 'DEMONSTRATE THAT YOU KNOWGOD', 'THOSE WHO KNOW GOD ENJOY BLESSINGS']
  read_scriptures: ['John 17:3', '1 John 2:4']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_001.pdf'
2:
  outline_name: 'WILL YOU BE A SURVIVOR OF THE LAST DAYS?'
  outline_date: '9/15'
  outline_time: 30
  outline_note: 'Convey the urgency of our times. Prove conclusively that we are living in the last days. Motivate audience to take positive action in order to be among the survivors.'
  subheadings: ['WE MUST BE CONCERNED ABOUT SURVIVING THE LAST DAYS', 'JESUS FORETOLD THE END OF THE JEWISH SYSTEM OF THINGS', 'PROPHECYABOUT CONCLUSION OF SYSTEM APPLIES TODAY', 'FURTHER PROOF THAT WE ARE LIVING IN “THE LAST DAYS”', 'ACTION IS REQUIRED IF WE ARE TO SURVIVE THE LAST DAYS']
  read_scriptures: ['Matthew 24:1-8', '2 Timothy 3:1', '2 Timothy 3:2-5', '2 Peter 3:11, 12a', '2 Peter 3:14']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_002.pdf'
3:
  outline_name: 'MOVE AHEAD WITH JEHOVAH’S UNIFIED ORGANIZATION'
  outline_date: '9/15'
  outline_time: 30
  outline_note: 'Build appreciation for the heavenly and earthly parts of Jehovah’s organization. Motivate the audience to become part of Jehovah’s organization in order to move ahead with it for all eternity!'
  subheadings: ['JEHOVAH IS A GOD OF ORGANIZATION', 'JEHOVAH’S ORGANIZATION IS UNIFIED', 'JEHOVAH’S ORGANIZATION IS DYNAMIC', 'KEEP ADVANCING WITH JEHOVAH’S ORGANIZATION']
  read_scriptures: ['Ephesians 1:8-10', 'Ephesians 4:1-3', 'Isaiah 60:17', 'Isaiah 60:22']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_003.pdf'
4:
  outline_name: 'EVIDENCE OF GOD IN THE WORLD AROUND US'
  outline_date: '9/15'
  outline_time: 30
  outline_note: 'Creation and the Bible provide evidence of God’s existence. Additionally, the dramatic changes made by some who have come to know and serve Jehovah point to wisdom and power beyond any human source. Motivate listeners to act on this evidence and to accept Jehovah’s guidance in their life.'
  subheadings: ['IT IS IMPORTANT TO EXAMINE EVIDENCE OF GOD’S EXISTENCE', 'CREATION GIVES EVIDENCE OFA CREATOR', 'CREATION REVEALS GOD’S QUALITIES', 'THE BIBLE GIVES EVIDENCE OFA DIVINE AUTHOR', 'LET THE CREATOR GUIDE YOUR LIFE']
  read_scriptures: ['Hebrews 3:4', 'Romans 1:20']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_004.pdf'
5:
  outline_name: 'REAL HELP FOR THE FAMILY'
  outline_date: '9/15'
  outline_time: 30
  outline_note: 'Warm, loving family relationships require time and effort, but they are achievable. Present a realistic view of challenges to family happiness. Instill confidence that problems can be solved by applying Bible principles.'
  subheadings: ['GOD WANTS YOUR FAMILY TO BE HAPPY', 'UNSELFISHNESS IS THE KEY TO A HAPPY FAMILY', 'CHALLENGES TO FAMILY HAPPINESS CAN BE OVERCOME', 'STRENGTHEN YOUR COMMITMENT TO YOUR FAMILY']
  read_scriptures: ['Colossians 3:14', 'Colossians 3:19, 21', 'Colossians 3:18', 'Colossians 3:20', 'Colossians 3:12', 'Colossians 3:13']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_005.pdf'
6:
  outline_name: 'THE FLOOD OF NOAH’S DAY AND YOU'
  outline_date: '9/15'
  outline_time: 30
  outline_note: 'Allow the Bible to convince the audience that (1) the Flood was a real, historical event, (2) Jehovah will destroy the present wicked world, and (3) survival depends on our cultivating and demonstrating faith like that of Noah.'
  subheadings: ['THE GLOBAL FLOOD WAS A HISTORICAL EVENT', 'DESTRUCTION OFAN UNGODLY WORLD SETS A PATTERN FOR OUR DAY', 'IMITATE NOAH’S FAITH IN ORDER TO SURVIVE', 'DO NOT MISS THE PURPOSE OF THE FLOOD ACCOUNT']
  read_scriptures: ['Matthew 24:37', '2 Peter 3:5-7', 'Hebrews 11:7']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_006.pdf'
7:
  outline_name: 'IMITATE “THE FATHER OF TENDER MERCIES”'
  outline_date: '12/15'
  outline_time: 30
  outline_note: 'Define mercy, using the Scriptures. Use Bible examples to show how Jehovah and Jesus demonstrated mercy. Finally, consider ways that we can imitate Jehovah’s mercy.'
  subheadings: ['WHAT IS MERCY?', 'JEHOVAH IS THE SOURCE OF TENDER MERCIES', 'JESUS PERFECTLY IMITATED HIS FATHER IN SHOWING MERCY', 'CONTINUE TO BE MERCIFUL IN IMITATION OF JEHOVAH']
  read_scriptures: ['2 Corinthians 1:3', 'Luke 6:36', '2 Corinthians 1:4']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_007.pdf'
8:
  outline_name: 'LIVING TO DO GOD’S WILL, NOT OUR OWN'
  outline_date: '9/15'
  outline_time: 30
  outline_note: 'Explain how mankind came under slavery to sin and how one can be set free by exercising faith in Christ’s ransom. Appreciation should move us to demonstrate our faith in the ransom by how we live.'
  subheadings: ['A SPIRIT OF INDEPENDENCE PERMEATES MODERN SOCIETY', 'TRUE FREEDOM INVOLVES DEPENDENCE ON GOD AND JESUS', 'LIVE DAILY TO DO JEHOVAH’S WILL', 'STRENGTHEN YOUR RESOLVE TO LIVE FOR GOD’S WILL']
  read_scriptures: ['Romans 6:16', 'Romans 6:23', '2 Corinthians 5:14, 15', 'Corinthians 6:18-20', 'Romans 6:22']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_008.pdf'
9:
  outline_name: 'BE A HEARER AND A DOER OF GOD’S WORD'
  outline_date: '12/16'
  outline_time: 30
  outline_note: 'Help the audience to see the vital need to listen attentively to Jehovah’s instruction, get the sense of it, and apply it. Emphasize the need to pay attention to how we listen when studying or attending meetings.'
  subheadings: ['“LET THE ONE WHO HAS EARS LISTEN”', 'HEARERS MUST ALSO BECOME DOERS OF THE WORD', 'DOERS OF THE WORD SHARE THE KINGDOM MESSAGE WITH OTHERS', '“PAYATTENTION TO HOW YOU LISTEN”', 'THOSE WHO APPLY GOD’S WORD WILL BE BLESSED']
  read_scriptures: ['James 1:25', 'Matthew 7:24']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_009.pdf'
10:
  outline_name: 'BE HONEST IN ALL YOU SAY AND DO'
  outline_date: '12/16'
  outline_time: 30
  outline_note: 'Motivate the audience to imitate Jehovah, “the God of truth.” Emphasize the benefits of honesty, including gaining Jehovah’s friendship and bringing honor to him.'
  subheadings: ['DO YOU VIEW HONESTY AS GOD DOES?', 'BE HONEST WITH YOURSELF', 'BE HONEST IN THE FAMILY AND WITH OTHERS', 'REWARDS OF HONESTY']
  read_scriptures: ['Hebrews 13:18', 'Psalm 139:23, 24', 'Proverbs 11:1', ]
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_010.pdf'
11:
  outline_name: '“NO PART OF THE WORLD”—IN IMITATION OF CHRIST'
  outline_date: '12/16'
  outline_time: 30
  outline_note: 'Discuss Christ’s example. Help the audience to understand in practical ways what it means to be no part of the world, using local examples where possible.'
  subheadings: ['“NO PART OF THE WORLD”—WHY?', 'JESUS SHOWED US HOW TO REMAIN “NO PART OF THE WORLD”', 'CONQUER THE WORLD, AS JESUS DID', 'THIS WICKED WORLD IS SOON TO END!']
  read_scriptures: ['John 17:16', 'John 16:33', '1 John 5:3, 4', '1 John 2:17']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_011.pdf'
12:
  outline_name: 'YOUR VIEW OF AUTHORITY MATTERS TO GOD'
  outline_date: '12/16'
  outline_time: 30
  outline_note: 'Help the audience to appreciate that the Supreme Authority, Jehovah God, wants us to respect authority that he permits to exist. We must demonstrate respect in our attitude and actions.'
  subheadings: ['WHY RESPECT AUTHORITY?', 'SHOW RESPECT FOR AUTHORITY IN THE FAMILY', 'SHOW RESPECT FOR “THE SUPERIOR AUTHORITIES”', 'SHOW RESPECT FOR THE SUPREME AUTHORITY', 'JEHOVAH’S AUTHORITY WILL LAST FOREVER']
  read_scriptures: ['Proverbs 24:21', 'Romans 13:1, 2', 'Hebrews 13:17']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_012.pdf'
13:
  outline_name: 'A GODLY VIEW OF SEX AND MARRIAGE'
  outline_date: '12/16'
  outline_time: 30
  outline_note: 'Discuss this topic with dignity and candor. Help the audience to see the wisdom of cultivating self-control and following Jehovah’s loving and balanced guidance.'
  subheadings: ['SEX AND MARRIAGE—LOVING GIFTS FROM OUR CREATOR', 'GODLY ADVICE HELPS TO MAKE MARRIAGE A SUCCESS', 'GOD’S VIEW OF SEX BENEFITS SINGLE PEOPLE', 'PEACE AND HAPPINESS COME FROM HAVING GOD’S VIEW']
  read_scriptures: ['Colossians 3:5, 6', '1 Corinthians 7:3-5', 'Hebrews 13:4', 'Matthew 19:9', '1 Thessalonians 4:3-5', 'Psalm 19:9-11']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_013.pdf'
14:
  outline_name: 'A CLEAN PEOPLE HONORS JEHOVAH'
  outline_date: '10/18'
  outline_time: 30
  outline_note: 'Explain why it is necessary and beneficial for servants of Jehovah to be physically clean and free from defiling habits. Uphold Jehovah’s high standards while adapting the material to local needs and circumstances.'
  subheadings: ['WE MUST BE HOLY BECAUSE JEHOVAH IS HOLY', 'BE PHYSICALLY CLEAN AND ORDERLY', 'KEEP FREE FROM “EVERY DEFILEMENT OF FLESH AND SPIRIT”', 'MAINTAIN YOUR CLEAN STANDING BEFORE GOD']
  read_scriptures: ['1 Peter 1:15, 16', '1 Corinthians 14:33, 40', '2 Corinthians 7:1']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_014.pdf'
15:
  outline_name: '“WORK WHAT IS GOOD TOWARD ALL”'
  outline_date: '12/16'
  outline_time: 30
  outline_note: 'Explain how we can imitate Jehovah’s goodness by caring for others in practical ways. Emphasize that goodness is an aspect of the fruitage of God’s holy spirit.'
  subheadings: ['JEHOVAH TEACHES US BY EXAMPLE HOW TO DO GOOD TO OTHERS', 'DO GOOD TO YOUR FAMILY', 'DO GOOD TO FELLOW BELIEVERS', 'DO GOOD TO THOSE YOU DO NOT KNOW', 'DO GOOD TO OTHERS BY KINGDOM PREACHING']
  read_scriptures: ['Hebrews 13:16', 'Galatians 6:10', 'Matthew 7:12']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_015.pdf'
16:
  outline_name: 'KEEP GROWING IN YOUR RELATIONSHIP WITH GOD'
  outline_date: '12/16'
  outline_time: 30
  outline_note: 'Encourage the audience to strengthen and deepen their relationship with God. Motivate them to train their conscience and grow to spiritual maturity.'
  subheadings: ['A GOOD RELATIONSHIP WITH GOD IS POSSIBLE', 'TRAIN YOUR CONSCIENCE', 'ADVANCE TO SPIRITUAL MATURITY', 'CONTINUE TO GROW IN YOUR RELATIONSHIP WITH GOD']
  read_scriptures: ['Genesis 1:27', 'Romans 2:14, 15', 'Hebrews 5:14–6:1', 'Ephesians 4:13, 15']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_016.pdf'
17:
  outline_name: 'GLORIFYING GOD WITH ALL WE HAVE'
  outline_date: '4/18'
  outline_time: 30
  outline_note: 'Explain why we should glorify God and how doing so should affect our entire life. Help those newly associated to appreciate that members of the Christian congregation do not promote themselves or seek their own glory.'
  subheadings: ['JEHOVAH DESERVES TO BE GLORIFIED', 'IMITATE JESUS’ EXAMPLE OF GLORIFYING GOD', 'HOW WE CAN GLORIFY GOD WITH ALL WE HAVE', 'GLORIFYING GOD LEADS TO BLESSINGS']
  read_scriptures: ['Revelation 4:11', 'John 15:8', 'Mark 12:30']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_017.pdf'
18:
  outline_name: 'MAKE JEHOVAH YOUR STRONGHOLD'
  outline_date: '4/18'
  outline_time: 30
  outline_note: 'Explain that making Jehovah our stronghold involves all aspects of life. By submitting to God’s guidance and trusting in him fully now, we can enjoy his favor and hope to be preserved through the great tribulation.'
  subheadings: ['FUTURE SURVIVAL DEPENDS ON MAKING JEHOVAH YOUR STRONGHOLD', 'WORK HARD TO GAIN JEHOVAH’S APPROVAL', 'RELY ON JEHOVAH DURING TIMES OF DIFFICULTY', 'JEHOVAH WILL PROVE LOYAL TO THOSE MAKING HIM THEIR STRONGHOLD']
  read_scriptures: ['Nahum 1:6, 7', 'Proverbs 10:29', 'Proverbs 18:11', 'Psalm 37:39, 40']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_018.pdf'
19:
  outline_name: 'Your Future—How Can It Be Known?'
  outline_date: '1/20'
  outline_time: 30
  outline_note: 'Explain the prophecy of Daniel chapter 2 with clarity and enthusiasm. Build the audience’s confidence in fulfilled prophecy, and thus encourage them to have faith in prophecies yet to be fulfilled. At appropriate points during your talk, you may use the artwork provided to illustrate the contents of Nebuchadnezzar’s dream.'
  subheadings: ['KNOWLEDGE OF THE FUTURE HAS GREAT VALUE', 'JEHOVAH GOD REVEALS THE FUTURE', 'GOD’S KINGDOM ALONE WILL STAND FOREVER', 'SHOW YOUR FAITH IN GOD’S PROMISES FOR THE FUTURE']
  read_scriptures: ['Isaiah 42:9', 'Daniel 2:44, 45']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_019.pdf'
20:
  outline_name: 'IS IT TIME FOR GOD TO RULE THE WORLD?'
  outline_date: '7/18'
  outline_time: 30
  outline_note: 'Clearly present the Scriptural evidence that God’s Kingdom was established in 1914, and explain what the Kingdom will do in the near future.'
  subheadings: ['MANKIND NEEDS BETTER RULERSHIP', 'DANIEL CHAPTER 4—A PROPHETIC DREAM ABOUT RULERSHIP', 'THE DREAM FORETELLS THE RULE OF GOD’S KINGDOM', 'GOD’S KINGDOM WILL SOON TAKE FULL CONTROL']
  read_scriptures: ['Daniel 4:20-27', 'Ezekiel 21:26, 27', 'Luke 21:24']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_020.pdf'








200:
  outline_name: ''
  outline_date: ''
  outline_time: 
  outline_note: '.'
  subheadings: []
  read_scriptures: []
  file_location: ''