1:
  outline_name: 'HOW WELL DO YOU KNOW GOD?'
  outline_date: '9/15'
  outline_time: 30
  outline_note: 'Knowing God involves more than knowing facts about him. We must become intimately acquainted with Jehovah’s deeds and qualities and act in harmony with that knowledge. Motivate listeners to come to know Jehovah well and gain his approval.'
  subheadings: ['COMING TO KNOWGOD “MEANS EVERLASTING LIFE”', 'HOWCAN YOU COME TO KNOW JEHOVAH?', 'DEMONSTRATE THAT YOU KNOWGOD', 'THOSE WHO KNOW GOD ENJOY BLESSINGS']
  read_scriptures: ['John 17:3', '1 John 2:4']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_001.pdf'
2:
  outline_name: 'WILL YOU BE A SURVIVOR OF THE LAST DAYS?'
  outline_date: '9/15'
  outline_time: 30
  outline_note: 'Convey the urgency of our times. Prove conclusively that we are living in the last days. Motivate audience to take positive action in order to be among the survivors.'
  subheadings: ['WE MUST BE CONCERNED ABOUT SURVIVING THE LAST DAYS', 'JESUS FORETOLD THE END OF THE JEWISH SYSTEM OF THINGS', 'PROPHECYABOUT CONCLUSION OF SYSTEM APPLIES TODAY', 'FURTHER PROOF THAT WE ARE LIVING IN “THE LAST DAYS”', 'ACTION IS REQUIRED IF WE ARE TO SURVIVE THE LAST DAYS']
  read_scriptures: ['Matthew 24:1-8', '2 Timothy 3:1', '2 Timothy 3:2-5', '2 Peter 3:11, 12a', '2 Peter 3:14']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_002.pdf'
3:
  outline_name: 'MOVE AHEAD WITH JEHOVAH’S UNIFIED ORGANIZATION'
  outline_date: '9/15'
  outline_time: 30
  outline_note: 'Build appreciation for the heavenly and earthly parts of Jehovah’s organization. Motivate the audience to become part of Jehovah’s organization in order to move ahead with it for all eternity!'
  subheadings: ['JEHOVAH IS A GOD OF ORGANIZATION', 'JEHOVAH’S ORGANIZATION IS UNIFIED', 'JEHOVAH’S ORGANIZATION IS DYNAMIC', 'KEEP ADVANCING WITH JEHOVAH’S ORGANIZATION']
  read_scriptures: ['Ephesians 1:8-10', 'Ephesians 4:1-3', 'Isaiah 60:17', 'Isaiah 60:22']
  file_location: '/congregation_operations/storage/public_talk_outlines/S-34_E_003.pdf'






200:
  outline_name: ''
  outline_date: ''
  outline_time: 
  outline_note: '.'
  subheadings: []
  read_scriptures: []
  file_location: ''